# Generated by Django 5.1.5 on 2025-01-17 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopee', '0002_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AlterField(
            model_name='userdata',
            name='phone_no',
            field=models.CharField(max_length=15),
        ),
    ]
