# Generated by Django 5.1.5 on 2025-01-17 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopee', '0003_delete_product_alter_userdata_phone_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('user', 'User'), ('admin', 'Admin')], default='user', max_length=10),
        ),
    ]
